#!/bin/sh
# Crontabs are located by default in /var/spool/cron/crontabs/
# The default configuration is also calling all the scripts in /etc/periodic/${period}
echo 'crond run'
if test -f ./setup; then
    source ./setup
fi

exec gosu root /usr/sbin/crond -fS
